### ISSUE TITLE
DenseInstance error : cannot find symbol

### ISSUE THREAD

**Issue by kaysush** [jmgomezh/tmweka#1]
I'm using Weka 3.6 and while I'm trying to use this code it gives me the error

``` Java
DenseInstance instance = new DenseInstance(2);
                ^
symbol:   class DenseInstance
location: class Classifier
Classifier.java:39: error: cannot find symbol
DenseInstance instance = new DenseInstance(2);
```

In-fact `DenseInstance` class is missing even from the documentation that shipped with my version of Weka.

**Comment by jmgomezh** [comment]
`DenseInstance` is available in WEKA 3.7. In WEKA 3.6 and below, you must use `Instance`.

Read about it at: http://jmgomezhidalgo.blogspot.com.es/2013/04/a-simple-text-classifier-in-java-with.html
